
name: Build IOS
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/ios/build
  cancel-in-progress: true

jobs:
  install-pods:
    runs-on: macos-15
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: Tuist/.build
          key: ${{ runner.os }}-${{ hashFiles('Tuist/Package.resolved') }}

    #   - name: Resolve dependencies
    #     if: steps.cache-restore.outputs.cache-hit != 'true'
    #     run: xcodebuild -resolvePackageDependencies -clonedSourcePackagesDirPath .build

      - name: Install Mise
        uses: jdx/mise-action@v2

      - name: Setup Registry
        run: tuist registry setup

      - name: Install Packages
        run: tuist install

      - name: Generate Project
        run: tuist install

      - name: Build
        run: tuist build

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: Tuist/.build
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
